### ISSUE TITLE
How to inject ISession into Repositories using IoC 

### ISSUE THREAD

**Issue by s-stude** [Byndyusoft/Byndyusoft.Dotnet.Core.Infrastructure#17]
Hi,

I've checked examples and have a question regarding `ISession` implementation for Dapper.NET. As far as I see `IRepository` will require `ISession` in the constructor. But `ISession` is created by `ISessionFactory`. 

How are you going to inject IRepository into a command, let's say if the repository itself is looking for `ISession` to be injected? 

And if a solution is to inject `ISessionFactory` into a repository to have the repository call `sessionFactory.Current` how are you implementing `ISessionFactory` in that case specifically for Dapper.NET to reference `Current` connection?

**Comment by s-stude** [comment]
Hello,

Thank you for your response. Here is my implementation based on your posts and comments. What do you think about it? I do not like it actually...

`ISessionProvider` is injectable with IoC now. And a repository/command can access a shared `ISession` created within `UnitOfWorkFactory`.

The problem here is that I have to register `ISessionProvider` and `ISessionFactory` as PerWebRequest lifetime within IoC. Otherwise, `CurrentSession` will be reassigned anytime I create a new session. 

What do you think? 

```
public interface ISessionProvider
    {
        ISession CurrentSession { get; }
    }

    public interface ISessionsFactory
    {
        ICommitableSession Create(IsolationLevel isolationLevel = IsolationLevel.ReadCommitted);
    }

    public class SqlSessionsFactory : ISessionsFactory, ISessionProvider
    {
        private readonly IDbConnectionsFactory _dbConnectionsFactory;
        private readonly ILogger _logger;
        public SqlSessionsFactory(IDbConnectionsFactory dbConnectionsFactory, ILogger logger)
        {
            if (dbConnectionsFactory == null)
                throw new ArgumentNullException(nameof(dbConnectionsFactory));

            _dbConnectionsFactory = dbConnectionsFactory;
            _logger = logger;
        }

        public ICommitableSession Create(
               IsolationLevel isolationLevel = IsolationLevel.ReadCommitted)
        {
            var connection = _dbConnectionsFactory.Create();
            var transaction = connection.BeginTransaction(isolationLevel);

            SqlSession sqlSession = new SqlSession(connection, transaction);

            this.CurrentSession = sqlSession; // <= This looks like a problem to maintain current session...

            return sqlSession;
        }

        public ISession CurrentSession { get; private set; }
    }
```
```
 public class UserRepository // : will be inherited from BaseRepository<T>
    {
        private readonly ISessionProvider _sessionProvider;
        private readonly ILogger _logger;

        public UserRepository(ISessionProvider sessionProvider, ILogger logger)
        {
            _sessionProvider= sessionProvider;
            _logger = logger;
        }

        public override void Save(User user)
        {
            using (var cmd = _sessionProvider.CurrentSession.CreateCommand())
            {
                // sopme logic here....
            }
        }
}
```

**Comment by govorovvs** [comment]
Hi, @s-stude 

And what about such approach?

    public class SqlSession : ICommitableSession, IDisposable
    {
        private static readonly AsyncLocal<SqlSession> _sCurrent = new AsyncLocal<SqlSession>();
        public SqlSession(connection, transaction) => _sCurrent.Value = this;
        public void Dispose() => _sCurrent.Value = null;
        public static SqlSession Current => _sCurrent.Value;
    }

    public class SqlSessionProvider : ISessionProvider
    {
        public ISession CurrentSession => SqlSession.Current;
    }

    public class SqlSessionsFactory : ISessionsFactory, ISessionProvider
    {
        public ICommitableSession Create(IsolationLevel isolationLevel = IsolationLevel.ReadCommitted)
        {
            //...
            return new SqlSession(connection, transaction); // assigns SqlSession.Current to one
        }
    }
`

**Comment by govorovvs** [comment]
... and service/controller/etc.

```
public class Service
{
    public void Action()
    {
        using (var session = _sessionFactory.Create())
        {
            _userRepository.Save(user);
            session.Commit();
        }
    }
}
```

**Comment by s-stude** [comment]
@govorovvs,

Right, almost the same I did, but for Service/ Controller /etc I use `UnitOfWork.Commit()` which holds session internally and commits it...

So.. your `SessionFactory` is pretty same as I did. But I have a question about `SqlSession`. In your example are you going to register `ISessionFactory` as a `SingleInstance` or `PerWebrequest` instance within IoC?

**Comment by govorovvs** [comment]
@s-stude  
as a `SingleInstance`

**Comment by s-stude** [comment]
Okay, then I do not understand how that will work in a single instance. 

If a session factory is a single instance and it does assign to its property a session like this `sessionFactory.CurrentSession = sqlSessionInstance;` then there might be a chance to have either `CurrentSession` to be `null` or to have a committed session. No?

**Comment by govorovvs** [comment]
Let's refactor my previous code

```
public class SqlSession : ICommitableSession, IDisposable
    {
        private static readonly AsyncLocal<SqlSession> _sCurrent = new AsyncLocal<SqlSession>();
        public void Dispose() => _sCurrent.Value = null;
        internal static SqlSession Current
        {
            get => _sCurrent.Value;
            set => _sCurrent.Value = value;
        }
    }

    public class SqlSessionsFactory : ISessionsFactory, ISessionProvider
    {
        public ICommitableSession Create(IsolationLevel isolationLevel = IsolationLevel.ReadCommitted)
        { 
            if (SqlSession.Current != null)
                throw new InvalidOperationException("Only one session per thread is allowed");

            SqlSession.Current = new SqlSession(connection, transaction); 
            return SqlSession.Current;
        }
        public ISession CurrentSession => SqlSession.Current;
    }
```

I store current `SqlSession` in the static Property `SqlSession.Current` and can access it anywhere in the current thread. This property is implemented via `AsyncLocal` object - `[ThreadLocal]` version which supports async/await, so each thread will have it's own `SqlSession.Current` instance. I reset current thread's `SqlSession.Current` value to null in the `SqlSession.Dispose` method, so in my approach its very important to create session inside 'using' context in service.

**Comment by s-stude** [comment]
Looks like `AsyncLocal<T>` does the whole trick. I'm not familiar with it so I'll go ahead and google that. 

Thank you for explaining this.
